version: "3.7"
services:

  nutriplan-pro:
    image: nutriplan-pro
    build:
      context: .
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    networks:
      - typebotnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=typebotnet
        - traefik.http.routers.nutriplan.rule=Host(`nutriplanpro.automatech.tech`)
        - traefik.http.routers.nutriplan.entrypoints=websecure
        - traefik.http.routers.nutriplan.tls.certresolver=letsencryptresolver
        - traefik.http.routers.nutriplan.service=nutriplan
        - traefik.http.services.nutriplan.loadbalancer.server.port=80

networks:
  typebotnet:
    external: true
    name: typebotnet
